#!/usr/bin/env bash
#
# reset-demo.sh — return the tutorial repo to its pre-run exercise state.
#
# Use this after ./run.sh if you want to run the workshop again from Sprint 1.
# It restores the tracked state files the Builder is allowed to edit, and removes
# generated app/test artifacts. It intentionally leaves node_modules/ and browser
# downloads alone so you do not pay the setup cost again.
#
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "✗ reset-demo.sh must run inside a git checkout."
  exit 1
fi

echo "Resetting Click Farm tutorial output..."

# These are the tracked files the Builder may update during a run.
git restore -- CLAUDE.md PROGRESS.md roadmap.md

# These are generated by the loop / QA agents and are intentionally not committed.
rm -rf index.html tests test-results playwright-report

echo "✓ Reset complete."
echo "Next: DEMO_MODE=planted ./run.sh"
